apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: ZjZkM2EwNDY0NjE1MjQwZGI4YTY0M2U=  # Base64-encoded storage account name
  azurestorageaccountkey: dTRRdEQyUk5KVGtyVzVybi9DL21OS3ZiYkNBK29ybmdZeGRYdG51QnhJcHM4V01IWHRkRW5kaHJ3cjZnTmFZaGhmRzF2UUNaQzlPK0FTdHMveElaZz09  # Base64-encoded storage account key