apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Make sure it points to nginx controller
  rules:
  - host: portfolio.example.com  # Your domain (or can use IP for now)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service  # Your backend service
            port:
              number: 80  # Port exposed by portfolio-service
