apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret  # Reference to the Kubernetes secret
    shareName: pvc-24aed6ba-6f64-4372-9038-a01001fd4199  # Name of the Azure File share
    readOnly: false