# Generated by Django 5.0.6 on 2025-02-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_languages_remove_skills_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ['-id']},
        ),
    ]
