# Generated by Django 5.0.6 on 2025-03-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_person_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={},
        ),
    ]
