# Generated by Django 5.0.6 on 2025-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_languages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='projects',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
