# Generated by Django 5.0.6 on 2025-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_projects_options_projects_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies used.', max_length=255, null=True),
        ),
    ]
