# Generated by Django 5.0.6 on 2025-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projects_github_url_projects_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skill_logos/'),
        ),
    ]
