# Generated by Django 5.0.6 on 2025-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skills_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='logo',
        ),
        migrations.AddField(
            model_name='skills',
            name='icon_class',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
