# Generated by Django 5.0.6 on 2025-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_skills_options_remove_skills_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ['position'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['position'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['position'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='languages',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
